[package]
name = "rust-chess-openings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.4.0"
shakmaty = "0.22.0"
